fixed timing and exit error code prompt

diff --git a/salt/files/home/dot_mac_salt/profile b/salt/files/home/dot_mac_salt/profile
--- a/salt/files/home/dot_mac_salt/profile
+++ b/salt/files/home/dot_mac_salt/profile
@@ -68,12 +68,11 @@ export GIT_PS1_SHOWDIRTYSTATE=true
 # export GIT_PS1_SHOWUPSTREAM="auto"
 export GIT_PS1_STATESEPARATOR=' '
 
-# Display unsuccessful exit codes
+# Display Unsuccessful Exit Codes
 function exit_status {
-  LAST_STATUS=$?
-  echo $LAST_STATUS
-  if [[ $LAST_STATUS != 0 ]]; then
-    echo "${Red}[Exit: $LAST_STATUS]"
+  last_status=$?
+  if [ $last_status -ne 0 ]; then
+    echo "[Exit: $last_status]"
   fi
 }
 
@@ -89,7 +88,7 @@ function timer_stop {
 
 trap 'timer_start' DEBUG
 
-PS1="\n${exit_status}${Green}--------------------[${TIMER_SHOW}s]------------------ \n${White}| \d \t \n| ${Red}\u${White}@${Cyan}\h ${Purple}\w ${White} \n| ${Yellow}\$(__git_ps1 "[%s]") ${White}=> ${NC}"
+PS1="\n${Red}\$(exit_status)${Green}--------------------[\${TIMER_SHOW}s]------------------ \n${White}| \d \t \n| ${Red}\u${White}@${Cyan}\h ${Purple}\w ${White} \n| ${Yellow}\$(__git_ps1 "[%s]") ${White}=> ${NC}"
 PS2="| => ${NC}"
 
 #   Set Paths
